language: python
sudo: false
python:
 - "3.5"
 - "3.4"
 - "3.3"
 - "2.7"
env:
 - DJANGO_VERSION=1.7.10
 - DJANGO_VERSION=1.8.5
install:
 - pip install coverage>=4.0
 - pip install flake8
 - pip install -q Django==$DJANGO_VERSION
matrix:
 exclude:
  - python: "3.5"
    env: DJANGO_VERSION=1.7.10
script:
 - coverage run setup.py test
 - flake8 registration
 - coverage report -m
